config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("genres/", include("categories.urls", namespace="genres")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search

app_name="core"

urlpatterns = [
  path("", resolve_home, name="home"),
  path("search", resolve_search, name="search")
]

movies/urls.py
from django.urls import path
from movies.views import MoviesView, MovieDetail, CreateMovie, UpdateMovie

app_name="movies"

urlpatterns = [
  path("", MoviesView.as_view(), name="movies"),
  path("<int:pk>", MovieDetail.as_view(), name="movie"),
  path("<int:pk>/update", UpdateMovie.as_view(), name="update"),
  path("create", CreateMovie.as_view(), name="create"),
]

movies/models.py
from django.urls import reverse
from django.db import models
from core.models import CoreModel

class Movie(CoreModel):

  """ Movie Model """

  title = models.CharField(max_length=120)
  year = models.IntegerField()
  cover_image = models.ImageField(null=True, blank=True)
  rating = models.IntegerField()
  category = models.ForeignKey("categories.Category", on_delete=models.CASCADE, related_name="movies")
  director = models.ForeignKey("people.Person", on_delete=models.CASCADE, related_name="movies")
  cast = models.ManyToManyField("people.Person")

  def __str__(self):
    return self.title

  def get_absolute_url(self):
    return reverse("movies:movie", kwargs={"pk": self.pk})

  class Meta:
    ordering = ["-created_at"]

movies/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView
from movies.models import Movie


class MoviesView(ListView):

    model = Movie
    paginate_by = 15
    paginate_orphans = 5
    ordering = "-created_at"
    context_object_name = "movies"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = "All Movies"
        return context


class MovieDetail(DetailView):
    model = Movie
    context_object_name = 'movie'


class CreateMovie(CreateView):
    model = Movie
    fields = (
        "title",
        "year",
        "cover_image",
        "rating",
        "category",
        "director",
        "cast",
    )


class UpdateMovie(UpdateView):
    model = Movie
    fields = (
        "title",
        "year",
        "cover_image",
        "rating",
        "category",
        "director",
        "cast",
    )

templates/movies/movie_detail.html
{% extends "base.html" %}

{% block page_title %}
  {{movie.title}}
{% endblock page_title %}

{% block content %}

<h2>{{movie.title}}</h2>
<a href="{% url 'movies:update' movie.pk %}">Edit Movie</a>

{% endblock content %}

templates/movies/movie_form.html
{% extends "base.html" %}

{% block page_title %}
  Movie
{% endblock page_title %}

{% block content %}

  {% include 'mixins/form.html' with form=form cta="Save" %}

{% endblock content %}

templates/movies/movie_list.html
{% extends "base.html" %}

{% block page_title %}
  Movies
{% endblock page_title %}

{% block content %}
<div>
  <h2 class="ml-1 text-3xl text-blue-600">Movies</h2>
  <div class="flex flex-wrap">    
  {% for movie in movies %}
  <div class="w-1/5 h-48 rounded shadow-lg p-2">
    <h3 class="text-gray-900 text-base mb-2"><a href="{% url 'movies:movie' movie.pk %}">{{movie.title}}</a></h3>
    <h5 class="inline-block bg-gray-200 rounded-full px-3 py-1 text-sm font-semibold text-gray-700 mr-2 mb-2">{{movie.year}}</h5>
  </div>
  {% endfor %}
  </div>
<hr />
</div>
<div class="mt-2 flex justify-center">
  <div>
  {% if page_obj.has_previous %}
        <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold py-1 px-2 rounded" href="?page={{page_obj.previous_page_number}}">Previous</a>
    {% endif %}

    <span class="font-bold text-blue-600">
    Page {{page_obj.number}} of {{page_obj.paginator.num_pages}}
    </span>

    {% if page_obj.has_next  %}
        <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold py-1 px-2 rounded" href="?page={{page_obj.next_page_number}}">Next</a>
    {% endif %}
  </div>
</div>
{% endblock content %}