books/urls.py
from django.urls import path
from books.views import BooksView, BookDetail, CreateBook, UpdateBook

app_name="books"

urlpatterns = [
  path("", BooksView.as_view(), name="books"),
  path("<int:pk>", BookDetail.as_view(), name="book"),
  path("<int:pk>/update", UpdateBook.as_view(), name="update"),
  path("create", CreateBook.as_view(), name="create"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("movies/", include("movies.urls", namespace="movies")),
    path("books/", include("books.urls", namespace="books")),
    path("genres/", include("categories.urls", namespace="genres")),
    path("people/", include("people.urls", namespace="people")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from core.views import resolve_home, resolve_search

app_name="core"

urlpatterns = [
  path("", resolve_home, name="home"),
  path("search", resolve_search, name="search")
]

movies/urls.py
from django.urls import path
from movies.views import MoviesView, MovieDetail, CreateMovie, UpdateMovie

app_name="movies"

urlpatterns = [
  path("", MoviesView.as_view(), name="movies"),
  path("<int:pk>", MovieDetail.as_view(), name="movie"),
  path("<int:pk>/update", UpdateMovie.as_view(), name="update"),
  path("create", CreateMovie.as_view(), name="create"),
]

people/urls.py
from django.urls import path
from people.views import PeopleView, PersonDetail, CreatePerson, UpdatePerson

app_name="people"

urlpatterns = [
  path("", PeopleView.as_view(), name="people"),
  path("<int:pk>", PersonDetail.as_view(), name="person"),
  path("<int:pk>/update", UpdatePerson.as_view(), name="update"),
  path("create", CreatePerson.as_view(), name="create"),
]

users/urls.py
from django.urls import path
from users.views import logout_view, LoginView, SignUpView, UserProfileView, UpdateProfileView, UpdatePasswordView

app_name="people"

urlpatterns = [
  path("logout", logout_view, name="logout"),
  path("login", LoginView.as_view(), name="login"),
  path("signup", SignUpView.as_view(), name="signup"),
  path("<int:pk>", UserProfileView.as_view(), name="profile"),
  path("update-profile/", UpdateProfileView.as_view(), name="update"),
  path("update-passwod/", UpdatePasswordView.as_view(), name="password"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="https://unpkg.com/tailwindcss@^1.0/dist/tailwind.min.css" rel="stylesheet">
	<style>
		input, select {
			width: 100%;
			padding-left: 0.75rem;
			padding-right: 0.75rem;
			padding-top: 0.5rem;
			padding-bottom: 0.5rem;
    }
	</style>
	<title>{% block page_title %}{% endblock page_title %} | Nomad Media</title>
</head>

<body>
	{% include 'partials/header.html' %} {% block content %} {% endblock content %} {% include 'partials/footer.html' %}
</body>

</html>

templates/genres.html
{% extends "base.html" %}

{% block page_title %}
  Search
{% endblock page_title %}


{% block content %}

<div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">

<form class="flex mb-2" method="GET"> 
  <input class="shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" type="text" name='name' placeholder="Search Movie, Book or Person" />
  <button class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white ml-2 py-2 px-4 border border-blue-500 hover:border-transparent rounded">Search</button>
</form>
</div>
<div class="block text-gray-700 text-sm font-bold mb-5 mt-10">Categories</div>
<div class="px-3">
  {%if books and movies%}
    <div class="flex align-center justify-center w-1/4 h-8 rounded text-white bg-indigo-500 text-lg">
      BOOK category
    </div>
    <br/>
    {%for book in books%}
      <div class="flex align-center justify-center w-1/2 h-8 truncate rounded text-white bg-purple-300 text-lg"><a href='{%url 'books:book' book.pk%}'>{{book.title}}</a></div>
    {%endfor%}
    <br/>
    <br/>
    <div class="block text-gray-700 text-sm font-bold mb-5 mt-10">MOVIE category</div>
    <br/>
    {%for movie in movies%}
      <div class="flex align-center justify-center w-1/2 h-8 truncate rounded text-white bg-purple-300 text-lg"><a href='{%url 'movies:movie' movie.pk%}'>{{movie.title}}</a></div>
    {%endfor%}
    <br/>
    <br/>
  {%elif books%}
    <div class="block text-gray-700 text-sm font-bold mb-5 mt-10">BOOK category</div>
    <br/>
    {%for book in books%}
      <div class="flex align-center justify-center w-1/2 h-8 truncate rounded text-white bg-purple-300 text-lg"><a href='{%url 'books:book' book.pk%}'>{{book.title}}</a></div>
    {%endfor%}
    <br/>
    <br/>
  {%elif movies%}
    <div class="block text-gray-700 text-sm font-bold mb-5 mt-10">MOVIE category</div>
    <br/>
    {%for movie in movies%}
      <div class="flex align-center justify-center w-1/2 h-8 truncate rounded text-white bg-purple-300 text-lg"><a href='{%url 'movies:movie' movie.pk%}'>{{movie.title}}</a></div>
    {%endfor%}
    <br/>
    <br/>
  {%endif%}
</div>

{% endblock content %}

templates/home.html
{% extends "base.html" %}

{% block page_title %}
  Home
{% endblock page_title %}

{% block content %}
<div class="m-1">
  <div class="flex items-center">
	<h2 class="text-3xl text-blue-600">Movies</h2> 
  <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold ml-2 py-2 px-4 rounded" href="{% url 'movies:create' %}">create</a>
  </div>
  <div class="flex flex-wrap">
	{% for movie in movies %}
    {% include "mixins/movie.html" with movie=movie %}
	{% endfor %}
  <div class="w-1/5 rounded shadow-lg p-2">
	<a class="text-blue-400" href="{% url 'movies:movies' %}">See all movies &rarr;</a>
  </div>
  </div>
</div>
	<hr />

<div class="m-1">
  <div class="flex items-center">
  <h2 class="text-3xl text-blue-600">Books</h2>
  <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold ml-2 py-2 px-4 rounded" href="{% url 'books:create' %}">create</a>
  </div>
  <div class="flex flex-wrap">
	{% for book in books %}
    {% include "mixins/book.html" with book=book %}
	{% endfor %}
  <div class="w-1/5 rounded shadow-lg p-2">
	<a class="text-blue-400" href="{% url 'books:books' %}">See all books &rarr;</a>
  </div>
  </div>
</div>
	<hr />

<div class="m-1">
  <div class="flex items-center">
	<h2 class="text-3xl text-blue-600">People</h2> 
  <a class="bg-blue-400 hover:bg-blue-600 text-white font-bold ml-2 py-2 px-4 rounded" href="{% url 'people:create' %}">create</a>
  </div>
  <div class="flex flex-wrap">
	{% for person in people %}
	  {% include "mixins/person.html" with person=person %}
	{% endfor %}
  <div class="w-1/5 rounded shadow-lg p-2">
	<a class="text-blue-400" href="{% url 'people:people' %}">See all people &rarr;</a>
  </div>
  </div>
</div>
	<hr />
{% endblock content %}

templates/search.html
{% extends "base.html" %}

{% block page_title %}
  Search
{% endblock page_title %}


{% block content %}

<div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">

<form class="flex mb-2" method="GET"> 
  <input class="shadow border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" type="text" name='name' placeholder="Search Movie, Book or Person" />
  <button class="bg-transparent hover:bg-blue-500 text-blue-700 font-semibold hover:text-white ml-2 py-2 px-4 border border-blue-500 hover:border-transparent rounded">Search</button>
</form>

<div class="block text-gray-700 text-sm font-bold mb-5 mt-10">Categories</div>
<div class="inline-block relative w-full flex flex-wrap">
  
{% for category in categories %}
  <div class="bg-orange-400 text-white px-5 shadow-md py-2 rounded-full mb-2 mr-2">
    <a href="{%url 'genres:categories' category.pk%}">{{category.name}}</a>
  </div>
{% endfor %}
  <br/>
  {%if people%}
    <div>
      <h3>PERSON</h3>
      {%for person in people%}
        <h4><a href='{%url 'people:person' person.pk%}'>{{person.name}}</a></h4>
      {%endfor%}
    </div>
    <br/>
  {%elif movies%}
    <div>
      <h3>MOVIE</h3>
      {%for movie in movies%}
        <h4><a href='{%url 'movies:movie' movie.pk%}'>{{movie.title}}</a></h4>
      {%endfor%}
    </div>
    <br/>
  {%elif books%}
    <div>
      <h3>BOOK</h3>
      {%for book in books%}
        <h4><a href='{%url 'books:book' book.pk%}'>{{book.title}}</a></h4>
      {%endfor%}
    </div>
    <br/>
  {%endif%}
  
</div>

{% endblock content %}